services:
    - mongodb

language: node_js
node_js:
    - "4"
    - "6"
    - "7"
before_script:
    - npm install
script:
    - npm test
after_script:
    - npm run coveralls

notifications:
  email:
    - lah_spfc2010@hotmail.com
    - isnack.yagami@gmail.com
    - edysegura@gmail.com
    - andremartinsgti@gmail.com
    - mecva@tmit.com.br
    
  on_success: always
